# ansible/vars/dotfiles.yml
dotfiles:
  - src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
  - src: ".tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
  - src: ".vimrc"
    dest: "{{ ansible_user_dir }}/.vimrc"
  - src: ".Xresources"
    dest: "{{ ansible_user_dir }}/.Xresources"
  - src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
  - src: "alacritty"
    dest: "{{ ansible_user_dir }}/.config/alacritty"
  - src: "fish"
    dest: "{{ ansible_user_dir }}/.config/fish"
  - src: "fuzzy_lock.sh"
    dest: "/usr/local/bin/fuzzy_lock.sh"
  - src: "hypr"
    dest: "{{ ansible_user_dir }}/.config/hypr"
  - src: "hypr"
    dest: "{{ ansible_user_dir }}/.config/hypr"
  - src: "i3"
    dest: "{{ ansible_user_dir }}/.config/i3"
  - src: "i3status-rust"
    dest: "{{ ansible_user_dir }}/.config/i3status-rust"
  - src: "i3status.conf"
    dest: "/etc/i3status.conf"
  - src: "kitty"
    dest: "{{ ansible_user_dir }}/.config/kitty"
  - src: "ligthdm"
    dest: "{{ ansible_user_dir }}/.config/ligthdm"
  - src: "picom"
    dest: "{{ ansible_user_dir }}/.config/picom"
  - src: "polybar"
    dest: "{{ ansible_user_dir }}/.config/polybar"
  - src: "ranger"
    dest: "{{ ansible_user_dir }}/.config/ranger"
  - src: "rofi"
    dest: "{{ ansible_user_dir }}/.config/rofi"
  - src: "touchpad_tapping.sh"
    dest: "/usr/local/bin/touchpad_tapping.sh"
  - src: "waybar"
    dest: "{{ ansible_user_dir }}/.config/waybar"
