pacman_packages:
  - alsa-utils
  - amd-ucode
  - ansible
  - arandr
  - audacity
  - awesome-terminal-fonts
  - base
  - base-devel
  - bash-completion
  - bluez-utils
  - brightnessctl
  - btop
  - cabextract
  - dmenu
  - dnsmasq
  - efibootmgr
  - ffmpeg4.4
  - firefox
  - foot
  - git
  - htop
  - i3-wm
  - i3lock
  - i3status
  - i3status-rust
  - kitty
  - kitty-shell-integration
  - kitty-terminfo
  - libmp4v2
  - lightdm
  - lightdm-gtk-greeter
  - lightsoff
  - linux
  - linux-firmware
  - man-db
  - mlocate
  - neofetch
  - networkmanager
  - openssh
  - p7zip
  - pavucontrol
  - powerline
  - powerline-fonts
  - polkit
  - ranger
  - sway
  - swaybg
  - swayidle
  - swaylock
  - telegram-desktop
  - tmux
  - ttf-font-awesome
  - unace
  - unarj
  - unp
  - unrar
  - vi
  - vim
  - vim-ansible
  - virt-manager
  - vlc
  - vulkan-mesa-layers
  - vulkan-radeon
  - waybar
  - wget
  - whois
  - wireless_tools
  - wmenu
  - alacritty
  - mako
  - slurp
  - waybar
  - sway-contrib
  - xorg-xwayland
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-wlr 
  - ranger 
  - atool 
  - elinks 
  - ffmpegthumbnailer 
  - highlight 
  - imagemagick 
  - libcaca 
  - lynx 
  - mediainfo 
  - odt2txt 
  - perl-image-exiftool 
  - poppler 
  - python-chardet 
  - python-pillow 
  - transmission-cli 
  - ueberzug 
  - w3m
  - wallutils
  - pulseaudio 
  - bemenu-wayland 
  - pulseaudio-bluetooth
  - feh
  - iw
  - waybar 
  - otf-font-awesome
  - ruby
  - python-pygments


yay_packages:
  - rofi-theme-launcher-1080p
  - rofi-theme-used
  - tempus-themes-kitty-git
  - ttf-font-icons
  - ttf-meslo-nerd-font-powerlevel10k
  - oh-my-zsh-git 
  - oh-myzsh-powerline-theme-git
  - zsh-theme-powerlevel10k-git
  - oh-my-zsh-powerline-theme-git 
  - bullet-train-oh-my-zsh-theme-git
