theme = "dracula"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
if_command = "mount|grep -i home"
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min} min, {max} max, {average} avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
if_command = "lspci|grep -i nvidia"
block = "nvidia_gpu"
label = "RTX 3070TI"
show_power_draw = true
interval = 1

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "external_ip"
format = "{ip} {country_code}"

[[block]]
block = "kdeconnect"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
