---
- name: Copy dotfiles to destination
  hosts: localhost
  #become: true

  vars_files:
    - ../ansible/vars/dotfiles.yml

  tasks:
    - name: Ensure dotfiles directory exists
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ dotfiles }}"
      when: item.dest | dirname != "~"

    - name: Copy dotfiles
      copy:
        src: "{{ playbook_dir }}/../ansible/files/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
      loop: "{{ dotfiles }}"
