---
- name: Copy dotfiles to destination
  hosts: localhost
  become: false 

  vars_files:
    - ../ansible/vars/dotfiles.yml

  tasks:
    - name: Ensure dotfiles directory exists
      file:
        path: "{{ item.dest | dirname }}"
        state: directory
        mode: '0755'
      loop: "{{ dotfiles }}"
      when: item.dest | dirname != "~"
      become: "{{ item.dest.startswith('/etc') or item.dest.startswith('/usr/local/bin') }}"

    - name: Copy dotfiles (without become)
      copy:
        src: "{{ playbook_dir }}/../ansible/files/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'
      loop: "{{ dotfiles }}"
      when: not (item.dest.startswith('/etc') or item.dest.startswith('/usr/local/bin'))

    - name: Copy system-wide config files (with become)
      copy:
        src: "{{ playbook_dir }}/../ansible/files/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: '0644'
      loop: "{{ dotfiles }}"
      when: item.dest.startswith('/etc') or item.dest.startswith('/usr/local/bin')
      become: true

