---
- name: Enable and start services
  hosts: localhost
  become: true

  vars_files:
    - ../ansible/vars/services.yml

  tasks:
    - name: Enable and start services from list
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"
