---
- name: Configuración inicial de Arch Linux
  hosts: localhost
  become: true

  vars:
    pacman_packages:
      - accerciser
      - alacritty
      - alsa-utils
      - amd-ucode
      - ansible
      - arandr
      - audacity
      - awesome-terminal-fonts
      - baobab
      - base
      - base-devel
      - bash-completion
      - bluez-utils
      - brightnessctl
      - btop
      - cabextract
      - cheese
      - code
      - d-spy
      - dconf-editor
      - devhelp
      - dmenu
      - dnsmasq
      - efibootmgr
      - endeavour
      - eog
      - epiphany
      - evince
      - evolution
      - ffmpeg4.4
      - file-roller
      - firefox
      - five-or-more
      - foot
      - four-in-a-row
      - fuzzel
      - fwupd
      - gdm
      - geary
      - gedit
      - ghex
      - gimp
      - git
      - gitg
      - glade
      - gnome-2048
      - gnome-backgrounds
      - gnome-boxes
      - gnome-builder
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - gnome-chess
      - gnome-clocks
      - gnome-color-manager
      - gnome-connections
      - gnome-console
      - gnome-contacts
      - gnome-control-center
      - gnome-devel-docs
      - gnome-dictionary
      - gnome-disk-utility
      - gnome-firmware
      - gnome-font-viewer
      - gnome-games
      - gnome-keyring
      - gnome-klotski
      - gnome-logs
      - gnome-mahjongg
      - gnome-maps
      - gnome-menus
      - gnome-mines
      - gnome-multi-writer
      - gnome-music
      - gnome-nibbles
      - gnome-notes
      - gnome-photos
      - gnome-recipes
      - gnome-remote-desktop
      - gnome-robots
      - gnome-session
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-extensions
      - gnome-software
      - gnome-sound-recorder
      - gnome-sudoku
      - gnome-system-monitor
      - gnome-taquin
      - gnome-terminal
      - gnome-tetravex
      - gnome-text-editor
      - gnome-tour
      - gnome-tweaks
      - gnome-user-docs
      - gnome-user-share
      - gnome-weather
      - grilo-plugins
      - grim
      - gvfs
      - gvfs-afc
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - hitori
      - htop
      - i3-wm
      - i3lock
      - i3status
      - i3status-rust
      - iagno
      - iwd
      - jdk-openjdk
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
      - libmp4v2
      - lightdm
      - lightdm-gtk-greeter
      - lightsoff
      - linux
      - linux-firmware
      - loupe
      - malcontent
      - man-db
      - mlocate
      - nano
      - nautilus
      - neofetch
      - networkmanager
      - openssh
      - orca
      - p7zip
      - pavucontrol
      - perl-anyevent-i3
      - perl-json-xs
      - polari
      - powerline
      - powerline-fonts
      - pycharm-community-edition
      - python-pygame
      - quadrapassel
      - rpi-imager
      - rygel
      - seahorse
      - sharutils
      - simple-scan
      - slurp
      - smartmontools
      - snapshot
      - steam
      - sushi
      - sway
      - swaybg
      - swayidle
      - swaylock
      - swell-foop
      - sysprof
      - tali
      - tecla
      - telegram-desktop
      - tilix
      - tmux
      - totem
      - tracker3-miners
      - transmission-gtk
      - ttf-font-awesome
      - unace
      - unarj
      - unp
      - unrar
      - vi
      - vim
      - vim-ansible
      - virt-manager
      - vlc
      - vulkan-mesa-layers
      - vulkan-radeon
      - waybar
      - wget
      - whois
      - wireless_tools
      - wmenu
      - xdg-desktop-portal-gnome
      - xdg-user-dirs-gtk
      - xdg-utils
      - xfsprogs
      - xorg-xwayland
      - xss-lock
      - yelp
      - zram-generator

  tasks:
    - name: Actualizar base de paquetes
      pacman:
        update_cache: yes

    - name: Instalar paquetes de Pacman
      pacman:
        name: "{{ pacman_packages }}"
        state: present

