---
- name: Installing pacman packages
  hosts: localhost
  become: true

  vars_files:
    - ../ansible/vars/packages.yml

  tasks:
    - name: Updating cache
      pacman:
        update_cache: yes

    - name: Installing packman packages
      pacman:
        name: "{{ pacman_packages }}"
        state: present

