---
- name: Configuración inicial de Arch Linux
  hosts: localhost

  vars_files:
    - packages.yml

  tasks:
    - name: Instalar paquetes de AUR con yay
      command:
        cmd: yay -S --noconfirm "{{ item }}"
      with_items: "{{ yay_packages }}"
      when: yay_packages | length > 0
